import assert from 'node:assert/strict'
import { chmodSync, mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { spawnSync } from 'node:child_process'
import test from 'node:test'

const cli = new URL('../src/cli.mjs', import.meta.url).pathname

/**
 * A consumer whose generated hook is installed and enabled, with a
 * machine-level pre-commit reachable through the global git config — the
 * exact topology where pointing core.hooksPath at .githooks used to silence
 * the machine's secret guard without a word from doctor.
 */
function consumer(t, hookBody) {
  const root = mkdtempSync(join(tmpdir(), 'foundry-doctor-hook-'))
  t.after(() => rmSync(root, { recursive: true, force: true }))
  mkdirSync(join(root, '.github/workflows'), { recursive: true })
  mkdirSync(join(root, '.githooks'), { recursive: true })
  writeFileSync(join(root, '.github/code-foundry.yml'), 'git_workflow: direct\n')
  writeFileSync(join(root, '.githooks/pre-commit'), hookBody)
  spawnSync('git', ['init', '-q'], { cwd: root })
  spawnSync('git', ['config', 'core.hooksPath', '.githooks'], { cwd: root })
  // The machine: a global hooks directory holding the kind of secret guard
  // the chaining exists to preserve.
  const machine = join(root, 'machine-hooks')
  mkdirSync(machine, { recursive: true })
  writeFileSync(join(machine, 'pre-commit'), '#!/bin/sh\nexit 0\n')
  chmodSync(join(machine, 'pre-commit'), 0o755)
  const gitconfig = join(root, 'machine-gitconfig')
  writeFileSync(gitconfig, `[core]\n\thooksPath = ${machine}\n`)
  return { root, gitconfig }
}

function runDoctor(root, gitconfig) {
  return spawnSync(process.execPath, [cli, 'doctor', '--target', root], {
    encoding: 'utf8',
    env: { ...process.env, GIT_CONFIG_GLOBAL: gitconfig },
  })
}

test('doctor warns when a machine-level pre-commit predates hook chaining', (t) => {
  const { root, gitconfig } = consumer(
    t,
    '#!/usr/bin/env sh\n# Generated by Code Foundry — see src/commands/sync.mjs.\nset -eu\nif [ -x node_modules/.bin/code-foundry ]; then\n  exec node_modules/.bin/code-foundry pre-commit\nfi\ngit diff --cached --check\n'
  )
  const result = runDoctor(root, gitconfig)
  assert.match(
    result.stderr + result.stdout,
    /machine-level pre-commit exists but the installed hook does not chain/,
    'the silent-disable class must be visible to doctor'
  )
})

test('doctor stays quiet when the installed hook chains to the machine', (t) => {
  const { root, gitconfig } = consumer(
    t,
    spawnSync('cat', [new URL('../.githooks/pre-commit', import.meta.url).pathname], {
      encoding: 'utf8',
    }).stdout
  )
  const result = runDoctor(root, gitconfig)
  assert.doesNotMatch(
    result.stderr + result.stdout,
    /machine-level pre-commit exists but the installed hook does not chain/
  )
})
