name: Release PR

on:
  push:
    branches: [staging]

permissions:
  contents: read
  pull-requests: write

jobs:
  release-pr:
    name: Release PR
    uses: ./.github/workflows/release-pr.yml
    with:
      runner: ubuntu-slim
    secrets: inherit
