name: Code Foundry Release Validation

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

permissions:
  actions: read
  contents: read
  packages: read
  security-events: write

jobs:
  ci:
    name: CI
    if: startsWith(github.head_ref, 'release-please--branches--main')
    uses: ./.github/workflows/ci.yml
    with:
      runtime-repository: 0xPlayerOne/code-foundry
      runtime-ref: main
      runner: ubuntu-latest
    secrets: inherit

  test:
    name: Test
    if: startsWith(github.head_ref, 'release-please--branches--main')
    uses: ./.github/workflows/test.yml
    with:
      runtime-repository: 0xPlayerOne/code-foundry
      runtime-ref: main
      runner: ubuntu-latest
      unit-runner: ubuntu-slim
    secrets: inherit

  security:
    name: Security
    if: startsWith(github.head_ref, 'release-please--branches--main')
    uses: ./.github/workflows/security.yml
    with:
      runtime-repository: 0xPlayerOne/code-foundry
      runtime-ref: main
      runner: ubuntu-slim
    secrets: inherit

  codeql:
    name: CodeQL
    if: startsWith(github.head_ref, 'release-please--branches--main')
    uses: ./.github/workflows/codeql.yml
    with:
      runtime-repository: 0xPlayerOne/code-foundry
      runtime-ref: main
      runner: ubuntu-latest
    secrets: inherit
