name: Code Foundry

on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main, staging]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml
    with:
      runtime-repository: 0xPlayerOne/code-foundry
      runtime-ref: ${{ github.sha }}
      runner: ubuntu-latest
      unit-runner: ubuntu-slim
    secrets: inherit
